- hosts: all
  become: yes
  roles:
    - create_user
  
- hosts: all
  become: yes
  roles:
    - kube_dependencies

- hosts: master
  become: yes
  roles:
    - master

- hosts: workers
  become: yes
  roles:
   - workers