
- name: get join command
  delegate_to: 23.97.169.174
  shell: kubeadm token create --v=5 --print-join-command
  register: join_command_ra
- name: set join command
  delegate_to: 23.97.169.174
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: TCP port 6443 on master is reachable from worker
  wait_for: "host={{ hostvars['master']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"
- name: join cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.log"
  args:
    chdir: /home/adminuser
    creates: node_joined.log